# Array

In [6]:
import numpy as np
x =[1,3,4,5]
y = np.array(x)
print(y)
print(type(y))
print(y.ndim)

[1 3 4 5]
<class 'numpy.ndarray'>
1


In [5]:
l = []
for i in range(1,5):
    int_1 =int(input("Enter a number :"))
    l.append(int_1)

print(np.array(l))

Enter a number : 13
Enter a number : 14
Enter a number : 15
Enter a number : 16


[13 14 15 16]


In [10]:
ar2 = np.array([[1,2,3,4],[1,2,3,4]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [12]:
ar3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(ar3)
print(ar3.ndim)
print(type(ar3))

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3
<class 'numpy.ndarray'>


In [18]:
arn = np.array([1,2,3,4],ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# zero

In [25]:
ar_one = np.ones(4)
print(ar_one)


[1. 1. 1. 1.]


# empty

In [26]:
ar_em = np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


#Range

In [55]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [29]:
ar_rn = np.arange(6)
print(ar_rn)

[0 1 2 3 4 5]


# Diagonal

In [31]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
ar_dia = np.eye(4)
print(ar_dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [34]:
ar_dia = np.eye(3,5)
print(ar_dia)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# linspace 

In [35]:
ar_lin = np.linspace(1,10,num = 5)
print(ar_lin)

[ 1.    3.25  5.5   7.75 10.  ]


In [36]:
ar_lin = np.linspace(0,10,num = 5)
print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]


In [37]:
ar_lin = np.linspace(0,20,num=5) 
print(ar_lin)

[ 0.  5. 10. 15. 20.]


# Random

Rand()

In [38]:
import numpy as np
var = np.random.rand(5)
print(var)


[0.04758053 0.30575541 0.84402824 0.70620911 0.6775696 ]


In [39]:
import numpy as np
var = np.random.rand(6)
print(var)

[0.01605087 0.71455235 0.22691725 0.50868173 0.37988662 0.5097637 ]


In [43]:
import numpy as np
var = np.random.rand(6)
print(var)    

[0.96577339 0.42873466 0.06321606 0.41553028 0.15291056 0.32339335]


In [44]:
var1 = np.random.rand(2,5)
print(var1)

[[0.07098832 0.65182718 0.37186028 0.27008843 0.87242968]
 [0.84731643 0.22394553 0.41326911 0.95039736 0.02884873]]


# Randn()

In [47]:
var2 = np.random.randn(5)
print(var2)

[ 0.00166079 -0.29219762  0.53897614  0.02371492  0.54635088]


In [48]:
var3 = np.random.randn(8)
print(var3)

[ 2.44822951  1.03522288 -0.86260756  0.7210303   0.04040727 -0.11806549
  0.96524862  0.2952874 ]


# ranf()

In [50]:
var4 = np.random.ranf(4)
print(var4)

[0.51552905 0.48660943 0.84202357 0.76332656]


In [51]:
var5 = np.random.ranf(7)
print(var5)

[0.91354011 0.0444097  0.79129835 0.60746053 0.31751468 0.62511265
 0.06762029]


# randint()

In [53]:
var6 = np.random.randint(5,20,5)
print(var6)var

[17 13 15  5  8]


In [54]:
var7 = np.random.randint(4,6,6)
print(var7)

[5 4 5 5 5 4]
