# Data type 

In [3]:
import  numpy as np
var = np.array([1,2,3,4])
print("Data type :",var.dtype)

Data type : int32


In [4]:
var = np.array([1.0,2.3,4.5,2.4])
print("Data Type :",var.dtype)

Data Type : float64


In [5]:
var = np.array (["A","B","c","d"])
print("Data Type :",var.dtype)


Data Type : <U1


In [6]:
var = np.array(["A","B","C","D",1,2,3,4])
print("Data Type :",var.dtype )

Data Type : <U11


In [7]:
 x = np.array([1,2,3,4])
print("Data Type :",x.dtype )

Data Type : int32


In [8]:
x = np.array([1,2,3,4],dtype = np.int8)
print("Data Type :",x.dtype )


Data Type : int8


In [9]:
x = np.array([1,2,3,4,5],dtype = np.int64)
print("Data Type :",x.dtype )

Data Type : int64


In [11]:
y =np. np.array([4,5,6,7,8,10],dtype = np.bool_)
print("Data Type :",y.dtype )

Data Type : bool


In [13]:
z = np.array([2,4,5,6,7],dtype  = np.intc)
print("Data Type :",z.dtype )
print(z)

Data Type : int32
[2 4 5 6 7]


In [15]:
x1 = np.array([1,3,4,5],dtype = "f")
print("Data Type :",x1.dtype)
print(x1)

Data Type : float32
[1. 3. 4. 5.]


In [17]:
x2 = np.array([1,2,3,4,6])
new = np.float32(x2)

                                   


print("Data Type :",x2.dtype )
print("Data Type :",new.dtype )
print(x2)
print(new)




Data Type : int32
Data Type : float32
[1 2 3 4 6]
[1. 2. 3. 4. 6.]


# Arithmetic opertion 

# array add in single line one d array

In [4]:
import numpy as np
var = np.array([1,2,3,4])

varadd = var + 3 
print(varadd)

[4 5 6 7]


In [6]:
var = np.array([1,2,3,4])
varadd = var + 2
print(varadd)

[3 4 5 6]


In [9]:
var = np.array([1,2,3,4,5])
varadd = var + 5
print(varadd)

[ 6  7  8  9 10]


# array addation in 1d array 

In [11]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = var1 + var2 
print(varadd)


[2 4 6 8]


In [12]:
var4 = np.array([4,5,6,7])
var5 = np.array([8,6,7,8])

varadd = var4 + var5
print(varadd)

[12 11 13 15]


# array subtiratiion in 1d array 

In [22]:
var6 = np.array([8,7,6,5])
var7 = np.array([8,7,6,5])

varsub  = var6  - var7 
print(varsub)



[0 0 0 0]


In [23]:
var8 = np.array([3,4,5,7])
var9 = np.array([8,7,5,4])

varsub = var8 - var9
print(varsub)

[-5 -3  0  3]


# Multiplay in 1d array 

In [24]:
var10 = np.array([1,2,3,4])
var11 = np.array([3,4,5,6])

varmlt = var10 * var11
print(varmlt)

[ 3  8 15 24]


In [25]:
var12 = np.array([1,2,4,5])
var13 = np.array([0,0,0,0])

varmlt = var12 * var13 
print(varmlt)


[0 0 0 0]


# divation on 1d array 

In [26]:
var14 = np.array([1,2,3,4])
var15 = np.array([1,2,3,4])

vardiv = var14 / var15
print(vardiv)

[1. 1. 1. 1.]


In [28]:
var16 = np.array([3,4,6,8])
var17 = np.array([2,3,5,6])

vardiv = var16/var17
print(vardiv)


[1.5        1.33333333 1.2        1.33333333]


In [30]:
var18 = np.array([0,8,9,0])
var19 = np.array([2,3,45,6])

vardiv = var18 / var19 
print(vardiv )

[0.         2.66666667 0.2        0.        ]


# modules in 1d array 

In [31]:
var20 = np.array([1,2,3,4])
var21 = np.array([1,2,3,4])

varmod = var20 % var21 
print(varmod)

[0 0 0 0]


In [32]:
var22 = np.array([2,3,4,5])
var23 = np.array([3,4,5,6])

varmod = var22 % var23 
print(varmod)


[2 3 4 5]


In [33]:
var24 = np.array([4,4,4,4])


varmod = var24 % 2
print(varmod)

[0 0 0 0]


# using funtionns in 1d array 

In [4]:
import numpy as np
var25 = np.array([2,3,4,5])
var26= np.array([2,5,6,7])

varadd = np.add(var25,var26)
print(varadd)


[ 4  8 10 12]


In [8]:
var26 = np.array([2,3,4,7])
var27 = np.array([2,3,4,7])

varsub = np.subtract(var26,var27)
print(varsub)

[0 0 0 0]


# 2D array in differnt opertion

In [3]:
import numpy as np
var27 = np.array([[1,2,3,4],[1,2,3,4]])
var28 = np.array([[1,2,3,4],[1,2,3,4]])

varadd2 = var27 + var28
print(varadd2)


[[2 4 6 8]
 [2 4 6 8]]


In [5]:
var29 = np.array([[1,2,3,4],[1,2,3,4]])
var30 = np.array([[1,2,3,4],[1,2,3,4]])

print(var29)
print()
print(var30)
print()

varadd3 = np.add(var29,var30)
print(varadd3)


[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


# mutiputions in 2d array 

In [6]:
var31 = np.array([[1,22,3,4],[1,2,3,4]])
var32 = np.array([[1,2,3,4],[1,2,3,5]])

print(var31)
print()
print(var32)
print()
varsub = np.multiply(var31,var32)
print(varsub)

[[ 1 22  3  4]
 [ 1  2  3  4]]

[[1 2 3 4]
 [1 2 3 5]]

[[ 1 44  9 16]
 [ 1  4  9 20]]
