# shape of numpy array (oder)

In [6]:
import numpy as np
var = np.array([[1,2],[1,2]])

print(var)
print()
print(var.shape )

[[1 2]
 [1 2]]

(2, 2)


In [7]:
var = np.array([[1,2,3,4,5,6],[3,4,5,56,7,8]])
print(var)
print()
print(var.shape)


[[ 1  2  3  4  5  6]
 [ 3  4  5 56  7  8]]

(2, 6)


In [9]:
var1 = np.array([1,2,3,4],ndmin = 4)

print(var1)
print(var1.ndim)
print()
print(var1 .shape)


[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


# Reshape(): it conver one dim to multidimation aray visevase

In [16]:
var3 = np.array([1,2,3,4,6,7])
print(var3)
print(var3.ndim)

print()

x = var3.reshape (3,2)
print(x)
print()
print(x.ndim)

[1 2 3 4 6 7]
1

[[1 2]
 [3 4]
 [6 7]]

2


 # Broadcasting in array

In [3]:
import numpy as np
var1 = np.array([1,2,3,4])   
print(var1.shape )
print()

var2 = np.array([4,5,6,7])

print(var1 + var2)


(4,)

[ 5  7  9 11]


In [7]:
import numpy as np
var2 = np.array([1,2,3])
print(var2.ahape)
print()
print(var2)
print()



var3 = np.array([[1],[3],[4]])
print(var2.shape)
print()
print(var3)

AttributeError: 'numpy.ndarray' object has no attribute 'ahape'

# Indexing and Slicing In NumPy Arrays 

# indexing (postive)

In [13]:
import numpy as np
var1= np.array([1,2,3,4,5])
print()
print("indexing is :",var1[1])



indexing is : 2


# negative indexing 

In [16]:
var2 = np.array([1,2,4,5,6,7,8])
print()
print("indexing is :",var2[-2])
print("indexing is :",var2[-4])



indexing is : 7
indexing is : 5


 # indexing in 2dim array 

In [23]:
var3 = np.array([[4,5,6],[6,7,8]])
print(var3)
print()
print("dim is :",var3.ndim)
print()
print("indixing is :",var3[0,1])
print("indixing is :",var3[1,0])
print("indixing is :",var3[1,2])


[[4 5 6]
 [6 7 8]]

dim is : 2

indixing is : 5
indixing is : 6
indixing is : 8


# 3 dim array

In [28]:
var4 = np.array([[[1,2],[9,5]]])
print(var4)
print()
print("dim is : ",var4.ndim)
print("indixing is :",var4[0,1,1])



[[[1 2]
  [9 5]]]

dim is :  3
indixing is : 5


In [29]:
var5  = np.array([[[1,2],[4,5]]])
print("insixing is :",var5[0,0,1])

insixing is : 2


# slicing in array 

In [33]:
var6 = np.array([1,2,3,4,5,6,7])
print(var6)
print()
print("slicing for 1 to 5 :",var6[0:5])

[1 2 3 4 5 6 7]

slicing for 2 to 5 : [1 2 3 4 5]


In [34]:
var6 = np.array([1,2,3,4,5,6,7])
print(var6)
print()
print("slicing for 2 to 6 :",var6[1:6])

[1 2 3 4 5 6 7]

slicing for 2 to 6 : [2 3 4 5 6]


In [37]:
var7 = np.array([1,2,3,4,5,6,7])
# print(var6)
print()
print("slicing for 2 to 7 :",var7[-1:-6:1])
# program not working (error )


slicing for 2 to 7 : []


In [43]:
var8 = np.array([1,2,3,4,5,6,7])
# print(var8)
print()
print("slicing for 2 to End :",var8[1:])
print("stop:",var8[::2])


slicing for 2 to End : [2 3 4 5 6 7]
stop: [1 3 5 7]


# slicing in 2dim array 

In [46]:
var9 = np.array([[1,2,4,5,6],[7,8,9,10,11],[12,13,14,15,16]])
print(var9)
print("8 to 5 :",var9[1,0:])  # it print all the element in given array 


[[ 1  2  4  5  6]
 [ 7  8  9 10 11]
 [12 13 14 15 16]]
8 to 5 : [ 7  8  9 10 11]


In [47]:
var9 = np.array([[1,2,4,5,6],[7,8,9,10,11],[12,13,14,15,16]])
print(var9)
print("8 to 5 :",var9[2,0:])  # it print all the element in given array 


[[ 1  2  4  5  6]
 [ 7  8  9 10 11]
 [12 13 14 15 16]]
8 to 5 : [12 13 14 15 16]


# Iterating in NumPy Arrays(loops)

# for one dim array 

In [2]:
import numpy as np
var9 = np.array([6,7,8,9,2,4])

for i in  var9:
    print(i)

6
7
8
9
2
4


In [8]:
import numpy as np
var10 = np.array([4,5,6,7,11,9])
for i in  var10:
    print(i)

4
5
6
7
11
9


# for 2dim array 

In [12]:
var11 = np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(var11)
print()

for j in var11:
    print(j)

print()
for i in var11:
      for l in i:
          print(l)

[[1 2 3 4 5]
 [4 5 6 7 8]]

[1 2 3 4 5]
[4 5 6 7 8]

1
2
3
4
5
4
5
6
7
8


In [14]:
var12 = np.array([[1,2,3,4,5],[6,7,7,8,9]])

for i in var12:
    print(i)
print()

for j in var12:
    for k in  j:
        print()


[1 2 3 4 5]
[6 7 7 8 9]


In [3]:
import numpy as np
var13 = np.array([[[2,4,5,7,7],[6,7,8,9,0]]])
print(var13)
print()



for j in var13:
    for k in j:
        for t in k:
            print(t)
        
        


[[[2 4 5 7 7]
  [6 7 8 9 0]]]

2
4
5
7
7
6
7
8
9
0


# for Iterating we use it [nditer()]

In [9]:
import numpy as np

var14 = np.array([[[4,5,6,7],[7,8,9,0]]])
print(var14)
print()
print(var14.ndim)
print()


for i in np.nditer(var14):
    print(i)


[[[4 5 6 7]
  [7 8 9 0]]]

3

4
5
6
7
7
8
9
0


In [6]:
import numpy as np
var14 = np.array([[2,3,4,5],[2,3,4,5]])
print(var14)
print()
print(var14.ndim)
print()

for i in np.nditer(var14):
    print(i)




[[2 3 4 5]
 [2 3 4 5]]

2

2
3
4
5
2
3
4
5


In [9]:
import numpy as np
var14 = np.array([[2,3,4,5],[2,3,4,5]])
print(var14)
print()
print(var14.ndim)
print()

for i,d in np.ndenumerate(var14):
    print(i,d)    # data + indaxing is shows 




[[2 3 4 5]
 [2 3 4 5]]

2

(0, 0) 2
(0, 1) 3
(0, 2) 4
(0, 3) 5
(1, 0) 2
(1, 1) 3
(1, 2) 4
(1, 3) 5


 # Copy vs Views Numpy(for copy any funtions or any thing  in numpy)

# copy () funtion 

In [14]:
import numpy as np
var15 = np.array([[1,3,4,5],[2,3,4,5]])
co = var15.copy()
print("var :",var15)
print("copy :",co)


var : [[1 3 4 5]
 [2 3 4 5]]
copy : [[1 3 4 5]
 [2 3 4 5]]


In [15]:
import numpy as np
var15 = np.array([1,3,4,5])
co = var15.copy()
print("var :",var15)
print("copy :",co)


var : [1 3 4 5]
copy : [1 3 4 5]


# view() funtion

In [17]:
x = np.array([5,6,7,8,9])
vi = x.view()
print("x :", x )
print("view :",vi )


x : [5 6 7 8 9]
view : [5 6 7 8 9]


# Joining & Split NumPy Arrays Using

# join arrray

# one 1dim array join 

In [1]:
import numpy as np

var1 = np.array([2,3,4,5])
var2 = np.array([6,7,8,9])

arr = np.concatenate((var1,var2))
print(arr)


[2 3 4 5 6 7 8 9]


In [2]:
import numpy as np

var1 = np.array([20,30,40,50])
var2 = np.array([60,70,80,0])

arr = np.concatenate((var1,var2))
print(arr)


[20 30 40 50 60 70 80  0]


# 2dim array 

In [5]:
var3 = np.array([[3,4,5,6],[7,8,9,0]])
var4 = np.array([[10,20,30,40],[50,60,60,70]])
arr_new = np.concatenate((var3,var4),axis = 1)
print(var3)
print()
print(var4)     # 1 ---> is  rows 
print()
print(arr_new) # 2 ---> columns 


[[3 4 5 6]
 [7 8 9 0]]

[[10 20 30 40]
 [50 60 60 70]]

[[ 3  4  5  6 10 20 30 40]
 [ 7  8  9  0 50 60 60 70]]


In [6]:
var3 = np.array([[3,4,5,6],[7,8,9,0]])
var4 = np.array([[10,20,30,40],[50,60,60,70]])
arr_new = np.concatenate((var3,var4),axis = 0)
print(var3)
print()
print(var4)     # 1 ---> is  rows 
print()
print(arr_new) # 2 ---> columns 


[[3 4 5 6]
 [7 8 9 0]]

[[10 20 30 40]
 [50 60 60 70]]

[[ 3  4  5  6]
 [ 7  8  9  0]
 [10 20 30 40]
 [50 60 60 70]]


# using stack funtions to join (marje)

In [2]:
import numpy as np 
var5  = np.array([2,3,4,5])
var6 =    np.array([6,7,8,9])

var_new = np.stack((var5,var6),axis = 1)   #stack is used for marjing  in axis (in array)
print(var_new)

[[2 6]
 [3 7]
 [4 8]
 [5 9]]


# without axis we can marje in rows or columns in array 

In [11]:
var7 = np.array([2,3,4,5])
var8 = np.array([6,7,8,9])    # it is marjing in rows 

var_new = np.hstack((var7,var8)) # ROWS 

var_new1 = np.vstack((var7,var8))# CLOUMNS 

var_new2 = np.dstack((var7,var9))# HEIGHT 

print(var_new)
print()
print(var_new1)
print()
print(var_new2)
print()

[2 3 4 5 6 7 8 9]

[[2 3 4 5]
 [6 7 8 9]]

[[[ 2 10]
  [ 3 11]
  [ 4 12]
  [ 5 13]]]



In [4]:
# it marjing in columns (in given array )
var9 = np.array([10,11,12,13])
var10 = np.array([14,15,16,17])

var_new = np.vstack((var9,var10))
print(var_new)


[[10 11 12 13]
 [14 15 16 17]]


# aplit array 

In [16]:
# spliting one dim array 
import numpy as np
var11 = np.array([1,2,3,4,5,6])
print(var11)
print()
new_sp = np.array_split(var11,6)  # 6 ---> is shows the array is split in 6 parts 
print(new_sp)
print()
print(type(new_sp))
print()
print(new_sp[0])  # inding of list 

[1 2 3 4 5 6]

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]

<class 'list'>

[1]


In [2]:
# spliting in 2 dim array (using slit () funtion )
import numpy as np
var12 = np.array([1,2,3,4,5,6])

print(var12)

print()
ar1 = np.array([[1,2],[3,4],[5,6]])
va1 = np.array_split(var12,3,axis = 1)
print(va1)



[1 2 3 4 5 6]



IndexError: tuple index out of range

# Search in numpy array

# for 1dim array 

In [2]:
import numpy as np
var1 = np.array([1,2,3,4,5,6,7])
print(var1)
print()
print

[1 2 3 4 5 6 7]


In [2]:
## import numpy as np
var2 = np.array([1,2,3,4,5,2,6,4,3,2,1,8])
a = np.where(var2 == 2)   # output comes indexing 
print(a)

(array([1, 5, 9], dtype=int64),)


In [3]:
## import numpy as np
var2 = np.array([1,2,3,4,5,2,6,4,3,2,1,8])
a = np.where((var2%2) == 2)   # output comes indexing 
print(a)

(array([], dtype=int64),)


# Search sorted array 

In [5]:
var3 = np.array([1,2,3,4,6,7,8,9])

z = np.searchsorted(var3,5)

print(z)


4


In [6]:
var3 = np.array([1,2,3,4,6,7,8,9])

z = np.searchsorted(var3,10) # inserting of 10 in array then shows the indixing is 8

print(z)


8


# Sort Array 

In [8]:
# shorting all the array in given bellow 
var4 = np.array([3,54,5,6,1,2,7,5,8,7,9])
print(var4)

print()

print(np.sort(var4))   # shoting funtions here use 

[ 3 54  5  6  1  2  7  5  8  7  9]

[ 1  2  3  5  5  6  7  7  8  9 54]


In [10]:
var5 = np.array(["a","r","b","d","c"])
print(var5)
print(np.sort(var5)) # shorting in array with string 
      

['a' 'r' 'b' 'd' 'c']
['a' 'b' 'c' 'd' 'r']


# 2 dim  array shorting in numpy 

In [12]:
var6 = np.array([[2,5,1],[5,3,2],[8,1,2]])
print(var6)
print(np.sort(var6))

[[2 5 1]
 [5 3 2]
 [8 1 2]]
[[1 2 5]
 [2 3 5]
 [1 2 8]]


In [15]:
var7 = np.array([[50,4,6],[11,5,6],[8,6,6]])
print(var7)
print(np.sort(var7))

[[50  4  6]
 [11  5  6]
 [ 8  6  6]]
[[ 4  6 50]
 [ 5  6 11]
 [ 6  6  8]]


 # filter array 

In [18]:
import numpy as np
var8 = np.array(["a","b","c","c"])
print(var8)
print()
f = [True,False,False,True]
new_a = var8[f]
print(new_a)



['a' 'b' 'c' 'c']

['a' 'c']


# numpy array funtions 

# Shuffle()

In [4]:
import numpy as np
var1 = np.array([1,2,3,5,6,7])
np.random.shuffle(var1)  # we suffle the array (we mix the in numpy array)
print(var1)

[5 1 6 7 3 2]


In [5]:
import numpy as np
var2 = np.array([10,20,30,40,50,60,70,70])
np.random.shuffle(var2)  # we suffle the array (we mix the in numpy array)
print(var2)

[30 20 40 50 10 60 70 70]


 # Unique()   fiuntions 

In [10]:
var3 = np.array([2,3,4,2,3,4,2,3,45,6,7,0,0,0])

x = np.unique(var3,return_index = True,return_counts= True) # in above given array we can write the unique elements in numpy array 
print(x)


(array([ 0,  2,  3,  4,  6,  7, 45]), array([11,  0,  1,  2,  9, 10,  8], dtype=int64), array([3, 3, 3, 2, 1, 1, 1], dtype=int64))


In [11]:
var4 = np.array([29,34,56,4,4,4,4,2,2,267,8,9,7,645,45,5,55,55,45,90,90])
print(var4)
print()
y = np.unique(var4)
print(y)

[ 29  34  56   4   4   4   4   2   2 267   8   9   7 645  45   5  55  55
  45  90  90]

[  2   4   5   7   8   9  29  34  45  55  56  90 267 645]


#  Resize() funtions 

In [3]:
import numpy as np
var5 = np.array([1,2,3,4,5,6])
print(var5)
print()

y = np.resize(var5,(2,3))  # (2,3)----> it shows the resize in rows and columns 
print(y)
print()

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]



In [6]:
import numpy as np
var5 = np.array([1,2,3,4,5,6])
print(var5)
print()

y = np.resize(var5,(3,3))  # (2,3)----> it shows the resize in rows and columns 
print(y)
print()

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]
 [1 2 3]]



In [7]:
import numpy as np
var5 = np.array([1,2,3,4,5,6])
print(var5)
print()

y = np.resize(var5,(3,2))  # (2,3)----> it shows the resize in rows and columns 
print(y)
print()

[1 2 3 4 5 6]

[[1 2]
 [3 4]
 [5 6]]



# flatten() funtions 


In [11]:
# the funtions shows that (it convert into 1dim into 2 two dim array )

var6 = np.array([1,2,3,4,5,6])
print(var6)
print()
y = np.resize(var6,(2,3))

print(y)
print()
print(y.flatten())
print()


[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]



#  NumPy Insert and Delete Arrays Functions

In [ ]:
# 

# The Concept of Matrix Numpy Arrays in Python

In [2]:
# creating a matrix in numpy array 
import numpy as np
var1 = np.matrix([[1,2,3],[4,5,6]])
print(var1)
print()
print(type(var1)) # here we are cheaking which type of data is 
print()

[[1 2 3]
 [4 5 6]]

<class 'numpy.matrix'>



# Arithmetic operation in matrix 

In [7]:
# The addictions of matrix (subtraiton is also )
var3 = np.matrix([[1,2,3],[4,5,6]])
var4 = np.matrix([[1,2,3],[4,5,6]])
print(var3)
print()
print(var4)
print()
print(var3 +var4)     # add
print()
print(var2 - var4) # sub 
print()

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]]

[[ 2  4  6]
 [ 8 10 12]]

[[0 0 0]
 [0 0 0]]



In [8]:
# multipations in matrix (using of funtions is [ dot() ] funtions )
var5 = np.matrix([[1,2],[2,4]])
var6 = np.matrix([[3,5],[1,2]])
print(var5)
print()
print(var6)
print()
print(var5*var6)  # normal multipation
print()
print(var5.dot(var6))  # mutipations using funtion
print()

[[1 2]
 [2 4]]

[[3 5]
 [1 2]]

[[ 5  9]
 [10 18]]

[[ 5  9]
 [10 18]]



In [4]:
# differance b/w matrix and array (data is same but data type  is differant )
var2 = np.array([[1,2,3],[4,5,6]])
print(var2)
print()
print(type(var2))
print()

[[1 2 3]
 [4 5 6]]

<class 'numpy.ndarray'>



# In matrix using diff funtion of numpy 

# 1 ---> Transpose () funtion

In [10]:
# another eaxmple 
var9 = np.matrix([[10,20,30],[40,50,60]])
print(var9)
print()
print(np.transpose(var9))
print()

[[10 20 30]
 [40 50 60]]

[[10 40]
 [20 50]
 [30 60]]



In [9]:
var8 = np.matrix([[1,2,3],[4,5,6]])
print(var8)
print()
print(np.transpose(var8))
print()

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]



In [11]:
# shortcut method to do transpose 
var8 = np.matrix([[1,2,3],[4,5,6]])
print(var8)
print()
print(var8.T)  # T is shortcut of transpose 
print()

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]



#  2 ---> Swapaxes () funtion 

In [13]:
#  it is just like transpose (in which rows change in cloumns or viesverse 
var9 = np.matrix([[1,2],[3,4]])
print(var9)
print()
print(np.swapaxes(var9,0,1))
print()

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]



# Inverse () (matrix funtion )

In [16]:
import numpy as np
var10 = np.matrix([[1,2],[3,4]])
print(var10)
print()

print(np.linalg.inv(var10))
print()

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]



# power () (Matrix funtion)